#!/usr/bin/env bash

case $1 in
    "list")
	while read p; do
	    echo $(basename $p)
	done < fterm-packages;;
    "install")
	foundpackage=0
        while read p; do
	    if [[ $(basename $p) == $2 ]]; then
                cd $(brew --prefix fterm)/bin/lib
		curl -O $p;

		# not accounting for 404 errors, but main package list is maintained
		if [ $? -ne 0 ]; then
		    echo "Insufficient permissions. Please run this command with sudo."
		fi
		
		cd -;
	    fi
	done < $(brew --prefix fterm)/bin/fterm-packages

	if [[ foundpackage == 1 ]]; then
	    echo "No such package '$2'."
	fi;;
    
     "uninstall")
	rm $(brew --prefix fterm)/bin/lib/$2;;

     *)
	 echo "f-p: command '$2' not found."
	  ;;
	
esac
